version: "2"

services:
        mariadb:
                image: mariadb:latest
                container_name: mariadb
                volumes:
                        - /home/shyeon/workspace/mysql:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: admin
                        MYSQL_USER: admin
                        MYSQL_PASSWORD: admin
                        MYSQL_DATABASE: metastore_db
                ports:
                        - 3306:3306
                healthcheck:
                        test: mysql -padmin -uadmin -e "SHOW DATABASES"
                        interval: 10s
                        timeout: 3s
                        retries: 3
        spark:
                # image: dream2globe/my-spark-env
                build: .
                container_name: mysparklab
                volumes:
                        - /home/shyeon/workspace/spark/SparkDefinitiveGuide:/home/jovyan/work
                ports:
                        - 8888:8888
                        - 4040:4040
                        - 4041:4041
                        - 9083:9083
                depends_on:
                        mariadb:
                                condition: service_healthy

